### ISSUE TITLE
Cant build data-generator !!!

### ISSUE THREAD

**Issue by girishkumarbk** [Azure/AI-PredictiveMaintenance#149]
Hi,

I'm trying to use the predictive maintenance data generator "https://github.com/Azure/AI-PredictiveMaintenance/tree/master/src/WebApp/App_Data/jobs/continuous/Simulator"
as a module in Azure IoT edge.  https://github.com/Azure/iotedge

In the current form, data generator creates Azure IoT hub devices and then creates the simulated devices and starts sending the data to IoT hub.  What I would want to do is to remove the IoThub interface from the data generator and just use the simulated devices to create the messages and publish the same to IoT edge Runtime broker. 

I tried to remove the IoT hub interfaces to build the module but am faced with some basic import issues like the one below ...      

---------------------------------
xxxx@VVVvm:~/cb/AI-PredictiveMaintenance/src$ python WebApp/App_Data/jobs/continuous/Simulator/simulator.py 
Traceback (most recent call last):
  File "WebApp/App_Data/jobs/continuous/Simulator/simulator.py", line 16, in <module>
    from devices import SimulatorFactory
  File "/home/netiotroot/cb/AI-PredictiveMaintenance/src/WebApp/App_Data/jobs/continuous/Simulator/devices/__init__.py", line 1, in <module>
    from devices.simulated_device import SimulatorFactory
  File "/home/netiotroot/cb/AI-PredictiveMaintenance/src/WebApp/App_Data/jobs/continuous/Simulator/devices/simulated_device.py", line 3, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC
xxxx@VVVvm:~/cb/AI-PredictiveMaintenance/src$

----------------------------

Questions:
1.0) Can we have the  instructions on how to build the WebApp jobs on Linux systems ?
2.0) Would it be possible to list down the steps, by the authors of predictive maintenance solution, on what it takes to convert the data generator as a IoT edge module which doesn't send messages to IoT hub but rather to the local pub/sub broker.

The predictive maintenance data generator is a very good use case to work on end to end flow and customize it for our needs. 

Hope to here on this soon

Regards,
/Girish BK

**Comment by girishkumarbk** [comment]
Any help from authors ?
