### ISSUE TITLE
linuxDsvmTemplate deployment failed

### ISSUE THREAD

**Issue by guybartal** [Azure/AI-PredictiveMaintenance#150]
Provision error:

```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n        \\\"message\\\": \\\"VM has reported a failure when processing extension 'pmmgzcvfoydwmm2'. Error message: \\\\\\\"Launch command failed: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/download/0/stdout'\\\\\\\".\\\"\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

```

![capture](https://user-images.githubusercontent.com/3179107/48073676-f0e47880-e1e7-11e8-8be6-422fc75a53c8.PNG)

**Comment by jenad1kr** [comment]
I am getting the same error. I tired West US 2, and I am still getting the same error. I pre-created the resource group, is that a problem?

**Comment by silviews** [comment]
Solved the above issue with a new Azure Databricks on West US 2 & a new solution deployment on West US 2

Error was: 
2019/05/16 13:25:15 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4] Comman d to execute:bash setup.sh https://westeurope.azuredatabricks.net ------
2019/05/16 13:25:16 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4]  Failed to launch command with error: [Errno 2] No such file or directory: '/var/ lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/download/0/stdou t',stacktrace: Traceback (most recent call last):
2019/05/16 13:25:16 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.Cust omScriptForLinux-1.5.4/Utils/ScriptUtil.py", line 51, in run_command
2019/05/16 13:25:16 ERROR:    LogUtil.tail(std_out_file), LogUtil.tail(err_out_f ile))
2019/05/16 13:25:16 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.Cust omScriptForLinux-1.5.4/Utils/LogUtil.py", line 27, in tail
2019/05/16 13:25:16 ERROR:    pos = min(output_size, os.path.getsize(log_file))
2019/05/16 13:25:16 ERROR:  File "/usr/lib/python2.7/genericpath.py", line 57, i n getsize
2019/05/16 13:25:16 ERROR:    return os.stat(filename).st_size
2019/05/16 13:25:16 ERROR:OSError: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/download/0/stdout'
2019/05/16 13:25:16 ERROR:
2019/05/16 13:25:16 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4] Daemon ,failed,1,Launch command failed: [Errno 2] No such file or directory: '/var/lib/ waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/download/0/stdout'

**Comment by lotevere** [comment]
I'm having this issue in any region that I've tried.  Any help?

**Comment by gr8sk8s** [comment]
> I'm having this issue in any region that I've tried. Any help?

Me too.  I'm not quite seeing the earlier errors, but I definitely see the final: 

 Error message: "Launch command failed: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.4/download/0/stdout'

The error seems pretty clear -- apparently the file is missing. But not sure why?
